; generated by a slicer
N10G90G21 ; compact post output
M140 S60
M104 S205
G28
G90
M82
G1 Z0.28 F2400
G1 X10.2 Y20.4 E0.1234 F1800
G2 X30 Y20 I10 J0 E0.42
M117 Printing layer 1
M118 E1 A1 action:notification Print_started
M486 S0 ABracket_left
N42 G1 X42.0 Y17.5*73
M104 S0 ; turn off hotend
M84

